server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: D:\REPOSITORIOS\PROYECTO\PROYECTO-MICROSERVICIOS\
          searchPaths: config-data
  security:
    user:
      name: root
      password: password