server:
  port: 8081

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: D:\REPOSITORIOS\CLOUDCONFIG\config-data
  security:
    user:
      name: root
      password: password